# Generated by Django 3.0.6 on 2020-06-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='insertUser',
        ),
    ]
