# Generated by Django 3.0.6 on 2020-06-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0002_auto_20200622_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipoAcesso',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('USR', 'Usuário')], default='USR', max_length=3),
        ),
    ]
