# Generated by Django 3.0.7 on 2020-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0004_auto_20201117_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
