# Generated by Django 3.2.8 on 2021-10-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0007_auto_20201119_0455'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
