# Generated by Django 3.0.7 on 2021-11-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
