# Generated by Django 3.0.7 on 2021-11-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0009_auto_20211119_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tipoAcesso',
            new_name='ADM',
        ),
    ]
