# Generated by Django 3.0.7 on 2021-11-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0010_auto_20211119_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ADM',
            new_name='is_staff',
        ),
    ]
