# Generated by Django 3.0.7 on 2021-11-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0011_auto_20211126_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@teste.com', max_length=120),
            preserve_default=False,
        ),
    ]
