# Generated by Django 3.0.7 on 2021-11-29 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controluser', '0012_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default=43999999999, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
            preserve_default=False,
        ),
    ]
