# Generated by Django 3.0.7 on 2020-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=120)),
                ('loginCliente', models.CharField(max_length=20)),
                ('senhaCliente', models.CharField(max_length=30)),
                ('cadastradoPor', models.CharField(max_length=30)),
                ('informServico', models.CharField(max_length=240)),
            ],
        ),
    ]
