# Generated by Django 3.0.7 on 2020-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlagenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='isEncerrado',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], default='NÃO', max_length=3),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='isReagendado',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], default='NÃO', max_length=3),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='solucao',
            field=models.CharField(default='A inserir', max_length=200),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipoPessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=3),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor',
            field=models.CharField(default='R$0,00', max_length=15),
        ),
    ]
