# Generated by Django 3.0.7 on 2021-12-06 00:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlagenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='encSla',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Final do SLA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cadastradoPor',
            field=models.CharField(max_length=30, verbose_name='Cadastrado por'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='endereco',
            field=models.CharField(max_length=120, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='informServico',
            field=models.CharField(max_length=240, verbose_name='Informações do Serviço'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='isEncerrado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Agendamento Encerrado?'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='isReagendado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Agendamento Reagendado?'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='loginCliente',
            field=models.CharField(max_length=20, verbose_name='Login do Cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='senhaCliente',
            field=models.CharField(max_length=30, verbose_name='Senha do Cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='solucao',
            field=models.CharField(default='A inserir', max_length=200, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipoPessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=3, verbose_name='Tipo de Pessoa'),
        ),
    ]
