# Generated by Django 3.0.7 on 2021-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlagenda', '0002_auto_20211205_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='encSla',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Final do SLA'),
        ),
    ]
