# Generated by Django 3.0.7 on 2020-09-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlagenda', '0002_auto_20200825_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
