# Generated by Django 3.0.7 on 2021-11-25 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlagenda', '0005_auto_20211125_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='isReagendado',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
    ]
